### ISSUE TITLE
Use pseudo-random colour scheme

### ISSUE THREAD

**Issue by rosscarter3** [rosscarter3/segcor#4]
Instead of using the colour scheme that maps to the cell ID directly, would be useful if we could use a pseudo-random colour scheme that maps 1:1 with cell ID to simplify the selection of neighbouring cells

**Comment by tjelvar-olsson** [comment]
Fixed with commit b5168a9

**Comment by rosscarter3** [comment]
Brilliant! Thanks Tjelvar
